# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a7a45552777544cb32f58cc7a06734c8"
name = "custify"
handle = "custify-8"
application_url = "https://spanish-howto-emissions-se.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = ["https://spanish-howto-emissions-se.trycloudflare.com/auth/callback", "https://spanish-howto-emissions-se.trycloudflare.com/auth/shopify/callback", "https://spanish-howto-emissions-se.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://spanish-howto-emissions-se.trycloudflare.com/apps/custify-proxy"
subpath = "custify"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
