name = "custify-app-block"
type = "theme_app_extension"

[build]
command = ""
watch = []

[[extensions]]
type = "theme_app_extension"
name = "Custify Rewards"
handle = "custify-rewards"

[extensions.settings]
include_app_block = true

[[extensions.blocks]]
type = "customer-rewards"
name = "Customer Rewards Block"